# Generated by Django 4.1.5 on 2023-01-09 16:54

import deals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Committent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("patronymic", models.CharField(max_length=100)),
                (
                    "registration_date",
                    models.DateField(auto_now=True, verbose_name="registration_date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission",
                    models.IntegerField(default=12, verbose_name="commission"),
                ),
                (
                    "date_start",
                    models.DateField(auto_now=True, verbose_name="deal_date_start"),
                ),
                ("date_close", models.DateField(verbose_name="deal_date_close")),
                (
                    "committent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="deals.committent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_text", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_number",
                    models.CharField(
                        default=deals.models.increment_product_code_number,
                        editable=False,
                        max_length=7,
                    ),
                ),
                ("price", models.IntegerField(verbose_name="price")),
                ("amount", models.IntegerField(default=1, verbose_name="amount")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="deals.deal"
                    ),
                ),
                (
                    "prod_inst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.productinstance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deal",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="deals.dealstatus"
            ),
        ),
    ]
