# Generated by Django 4.1.5 on 2023-01-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="date_close",
            field=models.DateField(
                blank=True, null=True, verbose_name="deal_date_close"
            ),
        ),
    ]
