# Generated by Django 4.1.5 on 2023-01-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_propertyinstance_prod_inst"),
        ("deals", "0004_alter_productelement_deal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productelement",
            name="prod_inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instance",
                to="products.productinstance",
            ),
        ),
    ]
