# Generated by Django 4.1.5 on 2023-01-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertytype",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
    ]
