# Generated by Django 4.1.5 on 2023-01-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_propertytype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyinstance",
            name="prod_inst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="property",
                to="products.productinstance",
            ),
        ),
    ]
